add Sidekiq and SendGrid
spark-solutions/heroku-buildpack-spree pull request #7
Opened 2019-09-26 15:10 UTC by chhga

2019-09-26 15:23 UTC, chhga commented
Regardless of those changes, a user still have to setup sendgrid api key manually.

2019-09-27 10:14 UTC, damianlegawiec requested changes

2019-09-27 10:14 UTC, damianlegawiec commented on lib/language_pack/spree.rb
> +gem 'sendgrid-ruby'
@chhga we don't need this, we're using sendgrid as a simple SMTP server

2019-09-27 14:37 UTC, damianlegawiec approved these changes

2019-09-27 14:38 UTC, merged